from cnpy import 图像处理


战斗性能 = 图像处理.读取图片("IMG\zdxn.png")
更换对手 = 图像处理.读取图片("IMG\ghds.png")
启航 = 图像处理.读取图片("IMG\qh.png")
继续 = 图像处理.读取图片("IMG\jx.png")
虚拟功勋 = 图像处理.读取图片("IMG\gx.png")
获得奖励 = 图像处理.读取图片("IMG\HDJL.png")
敌方 = 图像处理.读取图片("IMG\DF.png")
迎击 = 图像处理.读取图片("IMG\yj.png")
敌人 = 图像处理.读取图片("IMG\diren.png")
确定 = 图像处理.读取图片("IMG\qd.png")
失败 = 图像处理.读取图片("IMG\shibai.png")
军衔升级 = 图像处理.读取图片("IMG\jxsj.png")
MVP = 图像处理.读取图片("IMG\MVP.png")
更换队伍 = 图像处理.读取图片("IMG\ghdw.png")
更换队伍1 = 图像处理.读取图片("IMG\ghdw1.png")
掉落列表 = 图像处理.读取图片("IMG\dllb.png")
胜 = 图像处理.读取图片("IMG\sheng.png")
弹药耗尽 = 图像处理.读取图片("IMG\DYHJ.png")
跳过剧情 = 图像处理.读取图片("IMG\TGJQ.png")
防卫战 = 图像处理.读取图片("IMG\FWZ.png")
转盘 = 图像处理.读取图片("IMG\zhuanpan.png")
转盘暴击 = 图像处理.读取图片("IMG\zpbj.png")
抽奖券不足 = 图像处理.读取图片("IMG\cjqbz.png")
竞技倒计时 = 图像处理.读取图片("IMG\jjdjs.png")
钻石段位 = 图像处理.读取图片("IMG\ZSdw.png")
未到传说 = 图像处理.读取图片("IMG\WDCS.png")
无竞技次数 = 图像处理.读取图片("IMG\WJJCS.png")
添加竞技次数 = 图像处理.读取图片("IMG\TJJJCS.png")
推荐培养 = 图像处理.读取图片("IMG\Tuijianpeiyang.png")
指挥官 = 图像处理.读取图片("IMG\ZHG.png")